// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: arroyo.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UDPTunnelNewClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	RemotePort    uint32                 `protobuf:"varint,3,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPTunnelNewClient) Reset() {
	*x = UDPTunnelNewClient{}
	mi := &file_arroyo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPTunnelNewClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPTunnelNewClient) ProtoMessage() {}

func (x *UDPTunnelNewClient) ProtoReflect() protoreflect.Message {
	mi := &file_arroyo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPTunnelNewClient.ProtoReflect.Descriptor instead.
func (*UDPTunnelNewClient) Descriptor() ([]byte, []int) {
	return file_arroyo_proto_rawDescGZIP(), []int{0}
}

func (x *UDPTunnelNewClient) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *UDPTunnelNewClient) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *UDPTunnelNewClient) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

type UDPTunnelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IsResponse    bool                   `protobuf:"varint,2,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPTunnelData) Reset() {
	*x = UDPTunnelData{}
	mi := &file_arroyo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPTunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPTunnelData) ProtoMessage() {}

func (x *UDPTunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_arroyo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPTunnelData.ProtoReflect.Descriptor instead.
func (*UDPTunnelData) Descriptor() ([]byte, []int) {
	return file_arroyo_proto_rawDescGZIP(), []int{1}
}

func (x *UDPTunnelData) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *UDPTunnelData) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

func (x *UDPTunnelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UDPTunnelPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UDPTunnelPacket_NewClient
	//	*UDPTunnelPacket_Data
	Payload       isUDPTunnelPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPTunnelPacket) Reset() {
	*x = UDPTunnelPacket{}
	mi := &file_arroyo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPTunnelPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPTunnelPacket) ProtoMessage() {}

func (x *UDPTunnelPacket) ProtoReflect() protoreflect.Message {
	mi := &file_arroyo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPTunnelPacket.ProtoReflect.Descriptor instead.
func (*UDPTunnelPacket) Descriptor() ([]byte, []int) {
	return file_arroyo_proto_rawDescGZIP(), []int{2}
}

func (x *UDPTunnelPacket) GetPayload() isUDPTunnelPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UDPTunnelPacket) GetNewClient() *UDPTunnelNewClient {
	if x != nil {
		if x, ok := x.Payload.(*UDPTunnelPacket_NewClient); ok {
			return x.NewClient
		}
	}
	return nil
}

func (x *UDPTunnelPacket) GetData() *UDPTunnelData {
	if x != nil {
		if x, ok := x.Payload.(*UDPTunnelPacket_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUDPTunnelPacket_Payload interface {
	isUDPTunnelPacket_Payload()
}

type UDPTunnelPacket_NewClient struct {
	NewClient *UDPTunnelNewClient `protobuf:"bytes,1,opt,name=new_client,json=newClient,proto3,oneof"`
}

type UDPTunnelPacket_Data struct {
	Data *UDPTunnelData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UDPTunnelPacket_NewClient) isUDPTunnelPacket_Payload() {}

func (*UDPTunnelPacket_Data) isUDPTunnelPacket_Payload() {}

var File_arroyo_proto protoreflect.FileDescriptor

const file_arroyo_proto_rawDesc = "" +
	"\n" +
	"\farroyo.proto\x12\x06arroyo\"s\n" +
	"\x12UDPTunnelNewClient\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x1f\n" +
	"\vremote_addr\x18\x02 \x01(\tR\n" +
	"remoteAddr\x12\x1f\n" +
	"\vremote_port\x18\x03 \x01(\rR\n" +
	"remotePort\"a\n" +
	"\rUDPTunnelData\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x1f\n" +
	"\vis_response\x18\x02 \x01(\bR\n" +
	"isResponse\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x86\x01\n" +
	"\x0fUDPTunnelPacket\x12;\n" +
	"\n" +
	"new_client\x18\x01 \x01(\v2\x1a.arroyo.UDPTunnelNewClientH\x00R\tnewClient\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x15.arroyo.UDPTunnelDataH\x00R\x04dataB\t\n" +
	"\apayloadB\vZ\t/protocolb\x06proto3"

var (
	file_arroyo_proto_rawDescOnce sync.Once
	file_arroyo_proto_rawDescData []byte
)

func file_arroyo_proto_rawDescGZIP() []byte {
	file_arroyo_proto_rawDescOnce.Do(func() {
		file_arroyo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arroyo_proto_rawDesc), len(file_arroyo_proto_rawDesc)))
	})
	return file_arroyo_proto_rawDescData
}

var file_arroyo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_arroyo_proto_goTypes = []any{
	(*UDPTunnelNewClient)(nil), // 0: arroyo.UDPTunnelNewClient
	(*UDPTunnelData)(nil),      // 1: arroyo.UDPTunnelData
	(*UDPTunnelPacket)(nil),    // 2: arroyo.UDPTunnelPacket
}
var file_arroyo_proto_depIdxs = []int32{
	0, // 0: arroyo.UDPTunnelPacket.new_client:type_name -> arroyo.UDPTunnelNewClient
	1, // 1: arroyo.UDPTunnelPacket.data:type_name -> arroyo.UDPTunnelData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_arroyo_proto_init() }
func file_arroyo_proto_init() {
	if File_arroyo_proto != nil {
		return
	}
	file_arroyo_proto_msgTypes[2].OneofWrappers = []any{
		(*UDPTunnelPacket_NewClient)(nil),
		(*UDPTunnelPacket_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arroyo_proto_rawDesc), len(file_arroyo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arroyo_proto_goTypes,
		DependencyIndexes: file_arroyo_proto_depIdxs,
		MessageInfos:      file_arroyo_proto_msgTypes,
	}.Build()
	File_arroyo_proto = out.File
	file_arroyo_proto_goTypes = nil
	file_arroyo_proto_depIdxs = nil
}
